{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9c1c9ab0-d3db-45c6-99e6-ac054af8250a",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "import asyncio\n",
    "from playwright.async_api import async_playwright\n",
    "import pandas as pd\n",
    "from datetime import datetime\n",
    "import nest_asyncio\n",
    "import os\n",
    "import re\n",
    "import json\n",
    "import pytz\n",
    "from tqdm import tqdm\n",
    "from typing import List, Dict, Tuple\n",
    "\n",
    "# Разрешаем вложенные циклы событий для Jupyter/Облака\n",
    "nest_asyncio.apply()\n",
    "\n",
    "class FedresursBankruptcyChecker:\n",
    "    def __init__(self, client_file: str, headless: bool = True, delay: int = 3):\n",
    "        self.client_file = client_file\n",
    "        self.headless = headless\n",
    "        self.delay = delay\n",
    "        \n",
    "        # Настройка временной зоны Москвы\n",
    "        self.msk_tz = pytz.timezone('Europe/Moscow')\n",
    "        self.now = datetime.now(self.msk_tz)\n",
    "        self.today_str = self.now.strftime('%Y-%m-%d')\n",
    "        \n",
    "        # Пути к файлам\n",
    "        self.output_file = f\"reports/fedresurs_{self.today_str}.xlsx\"\n",
    "        self.history_file = \"history.json\"\n",
    "        self.results = []\n",
    "\n",
    "        # Твои ключевые фразы\n",
    "        self.key_phrases = [\n",
    "            \"Намерение должника обратиться в суд с заявлением о банкротстве\",\n",
    "            \"Намерение кредитора обратиться в суд с заявлением о банкротстве\",\n",
    "            \"Сообщение о судебном акте. о признании должника банкротом и открытии конкурсного производства\",\n",
    "            \"Сообщение о судебном акте. о введении наблюдения\",\n",
    "            \"Предстоящее исключение недействующего юридического лица из реестра\",\n",
    "            \"Направление в арбитражный суд заявления уполномоченного органа о признании должника банкротом\",\n",
    "            \"Уведомление о проведении собрания работников, бывших работников должника\",\n",
    "            \"Сведения о решениях, принятых собранием работников, бывших работников должника\",\n",
    "            \"Сообщение о результатах проведения собрания кредиторов\",\n",
    "            \"Сообщение о собрании кредиторов\"\n",
    "        ]\n",
    "\n",
    "        self.intent_phrases = [\"намерени\", \"исключение\"]\n",
    "\n",
    "        self.config = {\n",
    "            'search': {'id_patterns': [r'/companies/([a-f0-9-]{36})', r'data-company-id=[\"\\']([a-f0-9-]{36})[\"\\']']},\n",
    "            'sections': {\n",
    "                'bankruptcy': ['Сведения о банкротстве', 'Банкротство'],\n",
    "                'next_sections': ['Торги', 'Общая информация', 'Публикации', 'Обременения', 'ЕИО', 'Сведения о СРО', 'Членство в СРО', 'Лицензии']\n",
    "            },\n",
    "            'patterns': {\n",
    "                'case_number': r'([АA]\\d{2,}[-\\s]?\\d{2,}[-\\s]?\\d{4})',\n",
    "                'message': r'(\\d{8})\\s+от\\s+(\\d{2}\\.\\d{2}\\.\\d{4})'\n",
    "            }\n",
    "        }\n",
    "\n",
    "    def _clean_html(self, text: str) -> str:\n",
    "        text = re.sub(r'<[^>]+>', '', text)\n",
    "        text = re.sub(r'\\s+', ' ', text)\n",
    "        return text.strip()\n",
    "\n",
    "    def _extract_message_info(self, text: str) -> Dict[str, str]:\n",
    "        result = {'number': '', 'date': '', 'title': ''}\n",
    "        match = re.search(r'(\\d{8})\\s+от\\s+(\\d{2}\\.\\d{2}\\.\\d{4})', text)\n",
    "        if match:\n",
    "            result['number'] = match.group(1)\n",
    "            result['date'] = match.group(2)\n",
    "        for phrase in self.key_phrases:\n",
    "            if phrase.lower() in text.lower():\n",
    "                result['title'] = phrase\n",
    "                break\n",
    "        return result\n",
    "\n",
    "    def _is_intent(self, title: str) -> bool:\n",
    "        return any(phrase in title.lower() for phrase in self.intent_phrases)\n",
    "\n",
    "    def _extract_company_status(self, html: str) -> str:\n",
    "        status_match = re.search(r'info-item-name[^>]*>Статус<[^>]*>\\s*<[^>]*>\\s*<[^>]*>\\s*([^<]+)', html, re.I)\n",
    "        if status_match:\n",
    "            status_text = self._clean_html(status_match.group(1))\n",
    "            if status_text and status_text != \"нет данных\":\n",
    "                return status_text\n",
    "        return \"\"\n",
    "\n",
    "    def _extract_bankruptcy_data(self, html: str) -> Tuple[str, bool, List[Dict]]:\n",
    "        messages, case_number, status, has_data = [], \"\", \"\", False\n",
    "        company_status = self._extract_company_status(html)\n",
    "        if company_status and \"несостоятельным\" in company_status.lower():\n",
    "            status, has_data = company_status, True\n",
    "\n",
    "        for section_name in self.config['sections']['bankruptcy']:\n",
    "            pos = html.find(section_name)\n",
    "            if pos != -1:\n",
    "                end_pos = len(html)\n",
    "                for next_sec in self.config['sections']['next_sections']:\n",
    "                    next_pos = html.find(next_sec, pos + len(section_name))\n",
    "                    if next_pos != -1 and next_pos < end_pos: end_pos = next_pos\n",
    "                \n",
    "                section_html = html[pos:end_pos]\n",
    "                if 'нет данных' in self._clean_html(section_html).lower() and not has_data:\n",
    "                    return \"Нет данных\", False, []\n",
    "\n",
    "                case_match = re.search(self.config['patterns']['case_number'], section_html)\n",
    "                if case_match: case_number, has_data = case_match.group(1), True\n",
    "\n",
    "                if not status:\n",
    "                    for p in [r'конкурсное производство', r'введено наблюдение', r'внешнее управление']:\n",
    "                        if re.search(p, section_html, re.I):\n",
    "                            st_m = re.search(r'([^<>\\n]{0,70}(?:производство|наблюдение|управление)[^<>\\n]{0,70})', section_html, re.I)\n",
    "                            if st_m: status, has_data = self._clean_html(st_m.group(1)), True\n",
    "                            break\n",
    "\n",
    "                for match in re.finditer(self.config['patterns']['message'], section_html):\n",
    "                    m_num, m_date = match.groups()\n",
    "                    ctx = self._clean_html(section_html[max(0, match.start()-250):min(len(section_html), match.end()+250)])\n",
    "                    for ph in self.key_phrases:\n",
    "                        if ph.lower() in ctx.lower():\n",
    "                            messages.append({'number': m_num, 'date': m_date, 'title': ph, 'is_intent': self._is_intent(ph)})\n",
    "                            has_data = True\n",
    "                            break\n",
    "                break\n",
    "\n",
    "        if not has_data: return \"Нет данных\", False, []\n",
    "        \n",
    "        res = [\"Сведения о банкротстве:\"]\n",
    "        g1 = [case_number, status] + [f\"{m['number']} от {m['date']} {m['title']}\" for m in messages if not m['is_intent']]\n",
    "        if any(g1): res.append(f\"1) {' '.join(filter(None, g1))}\")\n",
    "        \n",
    "        intents = [m for m in messages if m['is_intent']]\n",
    "        if intents:\n",
    "            g2 = [\"Сообщения о намерении\"] + [f\"{m['number']} от {m['date']} {m['title']}\" for m in intents]\n",
    "            res.append(f\"2) {' '.join(g2)}\")\n",
    "        return '\\n'.join(res), True, messages\n",
    "\n",
    "    async def _load_all_publications(self, page) -> None:\n",
    "        for _ in range(10):\n",
    "            try:\n",
    "                btn = await page.wait_for_selector('div.more_btn:has-text(\"Загрузить еще\")', timeout=2000)\n",
    "                if btn and await btn.is_visible():\n",
    "                    await btn.click()\n",
    "                    await asyncio.sleep(1.5)\n",
    "                else: break\n",
    "            except: break\n",
    "\n",
    "    async def _extract_publications_from_page(self, url: str, browser) -> List[Dict]:\n",
    "        pubs = []\n",
    "        page = await browser.new_page()\n",
    "        try:\n",
    "            await page.goto(url, wait_until='networkidle', timeout=60000)\n",
    "            await self._load_all_publications(page)\n",
    "            cards = await page.query_selector_all('entity-card-publications-search-result-card')\n",
    "            for card in cards:\n",
    "                title_el = await card.query_selector('.fw-light')\n",
    "                if not title_el: continue\n",
    "                title = (await title_el.inner_text()).strip()\n",
    "                matched = next((p for p in self.key_phrases if p.lower() in title.lower()), None)\n",
    "                if matched:\n",
    "                    link_el = await card.query_selector('a.underlined')\n",
    "                    if link_el:\n",
    "                        msg_info = self._extract_message_info(await link_el.inner_text())\n",
    "                        if msg_info['number']:\n",
    "                            pubs.append({'number': msg_info['number'], 'date': msg_info['date'], 'title': matched, 'is_intent': self._is_intent(matched)})\n",
    "            pubs.sort(key=lambda x: datetime.strptime(x['date'], '%d.%m.%Y'), reverse=True)\n",
    "        finally: await page.close()\n",
    "        return pubs\n",
    "\n",
    "    async def _extract_trades_data(self, url: str, browser) -> List[Dict]:\n",
    "        trades = []\n",
    "        page = await browser.new_page()\n",
    "        try:\n",
    "            await page.goto(url, wait_until='networkidle', timeout=60000)\n",
    "            if await page.query_selector('div.info-header:has-text(\"Торги\")'):\n",
    "                cards = await page.query_selector_all('entity-card-biddings-block-bidding-card')\n",
    "                for card in cards:\n",
    "                    num_link = await card.query_selector('a.number-link')\n",
    "                    if num_link: trades.append({'number': await num_link.inner_text()})\n",
    "        except: pass\n",
    "        finally: await page.close()\n",
    "        return trades\n",
    "\n",
    "    async def find_company_id(self, inn: str, browser) -> str:\n",
    "        page = await browser.new_page()\n",
    "        try:\n",
    "            await page.goto(f\"https://fedresurs.ru/entities?searchString={inn}\", wait_until='networkidle', timeout=60000)\n",
    "            html = await page.content()\n",
    "            for pattern in self.config['search']['id_patterns']:\n",
    "                match = re.search(pattern, html)\n",
    "                if match: return match.group(1)\n",
    "        finally: await page.close()\n",
    "        return None\n",
    "\n",
    "    async def check_bankruptcy(self, inn: str, browser) -> Tuple[str, str]:\n",
    "        try:\n",
    "            c_id = await self.find_company_id(inn, browser)\n",
    "            if not c_id: return \"Компания не найдена\", \"\"\n",
    "            \n",
    "            main_url = f\"https://fedresurs.ru/companies/{c_id}\"\n",
    "            page = await browser.new_page()\n",
    "            await page.goto(main_url, wait_until='networkidle', timeout=60000)\n",
    "            main_html = await page.content()\n",
    "            await page.close()\n",
    "\n",
    "            b_status, has_d, b_msgs = self._extract_bankruptcy_data(main_html)\n",
    "            trades = await self._extract_trades_data(main_url, browser)\n",
    "            pubs = await self._extract_publications_from_page(f\"{main_url}/publications\", browser)\n",
    "\n",
    "            pub_lines = [f\"- {p['number']} от {p['date']} {p['title']}\" for p in pubs]\n",
    "            if (pubs or trades) and not has_d:\n",
    "                st = [\"Сведения о банкротстве:\"]\n",
    "                if trades: st.append(\"Торги присутствуют\")\n",
    "                if pubs: st.append(\"Публикации:\"); st.extend(pub_lines)\n",
    "                return \"\\n\".join(st), \"\"\n",
    "\n",
    "            return b_status if has_d or trades else \"Нет данных\", \"\\n\".join(pub_lines)\n",
    "        except Exception as e: return f\"Ошибка: {str(e)[:50]}\", \"\"\n",
    "\n",
    "    def generate_dashboard(self, history: Dict):\n",
    "        rows = \"\"\n",
    "        for date in reversed(sorted(history.keys())):\n",
    "            item = history[date]\n",
    "            badge = \"bg-danger\" if \"Есть изменения\" in item['status'] else \"bg-success\"\n",
    "            rows += f\"\"\"\n",
    "            <tr>\n",
    "                <td><strong>{date}</strong></td>\n",
    "                <td><span class=\"badge {badge}\">{item['status']}</span></td>\n",
    "                <td><a href=\"{item['file']}\" class=\"btn btn-sm btn-outline-light\">📥 Excel</a></td>\n",
    "            </tr>\"\"\"\n",
    "        \n",
    "        html = f\"\"\"\n",
    "        <!DOCTYPE html><html><head><meta charset=\"UTF-8\">\n",
    "        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\n",
    "        <style>body{{background:#121212;color:#e0e0e0;padding:50px 20px;}} .card{{background:#1e1e1e;border:1px solid #333;}} .table{{color:#e0e0e0;}}</style>\n",
    "        <title>Консоль Мониторинга</title></head><body><div class=\"container\" style=\"max-width:800px;\">\n",
    "        <h2 class=\"mb-4 text-center\"> Мониторинг Федресурс (Клиенты Х)</h2>\n",
    "        <div class=\"card shadow\"><table class=\"table table-hover mb-0\"><thead class=\"table-dark\">\n",
    "        <tr><th>Дата</th><th>Статус изменений</th><th>Отчет</th></tr></thead><tbody>{rows}</tbody></table>\n",
    "        </div></div></body></html>\"\"\"\n",
    "        with open(\"index.html\", \"w\", encoding=\"utf-8\") as f: f.write(html)\n",
    "\n",
    "    async def run(self):\n",
    "        if not os.path.exists('reports'): os.makedirs('reports')\n",
    "        df_input = pd.read_excel(self.client_file, header=5)\n",
    "        \n",
    "        # Автоопределение колонок\n",
    "        name_col = next(c for c in df_input.columns if 'Наименование' in str(c))\n",
    "        inn_col = next(c for c in df_input.columns if 'ИНН' in str(c))\n",
    "        \n",
    "        companies = df_input[[name_col, inn_col]].dropna()\n",
    "        companies.columns = ['name', 'inn']\n",
    "\n",
    "        async with async_playwright() as p:\n",
    "            browser = await p.chromium.launch(headless=self.headless)\n",
    "            for _, row in tqdm(companies.iterrows(), total=len(companies)):\n",
    "                status, pubs = await self.check_bankruptcy(str(row['inn']).strip(), browser)\n",
    "                self.results.append({'ИНН': row['inn'], 'Наименование': row['name'], 'Банкротство': status, 'Публикации': pubs})\n",
    "                await asyncio.sleep(self.delay)\n",
    "            await browser.close()\n",
    "\n",
    "        df_today = pd.DataFrame(self.results)\n",
    "        df_today.to_excel(self.output_file, index=False)\n",
    "\n",
    "        # Сравнение\n",
    "        if os.path.exists(self.history_file):\n",
    "            with open(self.history_file, 'r', encoding='utf-8') as f:\n",
    "                history = json.load(f)\n",
    "        else:\n",
    "            history = {}\n",
    "\n",
    "        dates = sorted(history.keys())\n",
    "        change_status = \"Базовый\"\n",
    "        if dates:\n",
    "            last_data = history[dates[-1]]['data']\n",
    "            # Сравниваем только значимое поле 'Банкротство'\n",
    "            change_status = \"Нет изменений\" if [r['Банкротство'] for r in last_data] == [r['Банкротство'] for r in self.results] else \"⚠️ Есть изменения\"\n",
    "\n",
    "        history[self.today_str] = {'status': change_status, 'file': self.output_file, 'data': self.results}\n",
    "        \n",
    "        with open(self.history_file, 'w', encoding='utf-8') as f:\n",
    "            json.dump(history, f, ensure_ascii=False)\n",
    "        \n",
    "        self.generate_dashboard(history)\n",
    "        print(f\"Готово! Статус: {change_status}\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    checker = FedresursBankruptcyChecker(client_file=\"Клиенты_страхование_ТЕСТ.xlsx\")\n",
    "    asyncio.run(checker.run())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "645876e9-7b26-4ad1-8b38-bcd7b562bc41",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
